all:
	gcc times2.c -o times2 -O3
	chmod +x ./times2
	./times2
	gcc gates.c -o gates -O3 -lm
	chmod +x ./gates
	./gates
times2: 
	gcc times2.c -o times2 -O3
	chmod +x ./times2
	./times2
gates: 
	gcc gates.c -o gates -O3 -lm
	chmod +x ./gates
	./gates

