[package]
name = "TapRec"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
crossterm = "0.28.1"
hound = "3.5.1"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
